import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Provider";
import Navbar from "@/components/Navbar";
import { TNav } from "@/components/TNav";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <TNav />
          <Navbar />
          <main className="border-b">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
