import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Provider";
import Navbar from "@/components/Navbar";
import { TNav } from "@/components/TNav";
import Footer from "@/components/Footer";
import { Bnav } from "@/components/Bnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="flex flex-col top-0 fixed z-50 items-center w-full">
          <TNav />
          <Navbar />
          <Bnav />
          </div>
          <main className="border-b pt-[146px]">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
